### ISSUE TITLE
Application Error on Login

### ISSUE THREAD

**Issue by MuhammadBayiz** [radityaharya/showtime#13]
Hi, i see that you put the app on running again and i wanted to migrate to showtime but when i login and authorize showtime in trakt after that i get this error
`Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1248548682`

**Comment by radityaharya** [comment]
Hey, can you try to log back in again?

**Comment by MuhammadBayiz** [comment]
Now it's logged in successfully, thanks for the quick fix

**Comment by MuhammadBayiz** [comment]
PS: the events show up in the dashboard of showtime

**Comment by radityaharya** [comment]
It seems like the requests are timing out. My guess is that it's due to Vercel's 10-second timeout per request because it doesn't have Trakt and TMDB data cached. Therefore, it has to fetch the data, which exceeds the execution time limit. Try re-adding the webcal after opening the dashboard to allow the backend to cache the data. I think I might have to decrease the default time range for the calendar endpoints

**Comment by MuhammadBayiz** [comment]
I tried re adding the webcal in the dashboard but no luck so i went and tried deleting showtime from connected apps in trakt and tried re connecting showtime but now it gives this error
```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1248548682
```

**Comment by MuhammadBayiz** [comment]
I've successfully logged in now
