### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by testbughub** [radityaharya/showtime#4]
First of all, I just have to say thank you for this.  
It's pretty much exactly what I've been wanting for so long.  

Unfortunately, I noticed that my calendar wasn't updating with the  
new shows I added, so I've been trying the last few days to  
re-create it. But every time I get this error:
```
Application error: a server-side exception has occurred (see the server logs for more information).

Digest: 1248548682
```

Hopefully it's an easy fix.  

Cheers!

**Comment by radityaharya** [comment]
Hi, I've noticed this issue on my Sentry dashboard for a while now and I've been meaning to reach out to you. It seems like your account is the only one having this problem. Upon further inspection there's a mismatch of id between the Users and Trakt account collection caused by the backward compatibility endpoint for trakt_ical users. For a quick fix, I'll try to stash your account and please try signing in again with your Trakt account.

**Comment by testbughub** [comment]
Huh, that's weird.  
I tried it again, but I'm getting a 504 Gateway time-out error now.

**Comment by testbughub** [comment]
Never mind, it worked now.  
Thank you very much for the fix, it is super appreciated!
