### ISSUE TITLE
Try signing in with a different account

### ISSUE THREAD

**Issue by Sp3EdeR** [radityaharya/showtime#9]
Dear Raditya,

Thank you for creating this tool and the accompanied website! It looks very good! Unfortunately I'm unable to log in. Please find the steps:

![image](https://github.com/radityaharya/showtime/assets/22780322/c34e61d6-d672-4c9f-87a0-d7a2751a25ce)
![image](https://github.com/radityaharya/showtime/assets/22780322/44ea209d-6148-47d3-a57d-d78f70e3c176)
![image](https://github.com/radityaharya/showtime/assets/22780322/5eaf8694-bc21-4042-b3c1-de87afa9047c)

After this process, I can find Showtime as under my connected apps in Trakt.

**Comment by radityaharya** [comment]
Hey, thanks for trying out Showtime. Due to the increase in users, my billing for MongoDB and Redis (which are hosted on Railway) has exceeded their $5 free limit, which means i'd have to pay for the rest. However, I want to be transparent about my current situation and express that I am unwilling to bear these costs any longer. Considering this, I might need to explore alternative solutions to manage expenses.

While I don't want to come across as pressuring for donations, I also want to point out that hey, selfhosting it is always an option

Thankyou for understanding 🙂
